# Generated by Django 5.1.7 on 2025-03-18 20:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_reservation_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='availability',
            name='available_from',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='availability',
            name='available_to',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='availability',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='api.workshop'),
        ),
        migrations.AlterField(
            model_name='workshopimage',
            name='image',
            field=models.ImageField(upload_to='workshop_photos/'),
        ),
    ]
