# Generated by Django 5.1.7 on 2025-03-23 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_workshopimage_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.workshop'),
        ),
    ]
